language: csharp
solution: OnionArchitecture.sln
install:
  - nuget restore OnionArchitecture.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release OnionArchitecture.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./OnionArchitecture.Core.Tests/bin/Release/OnionArchitecture.Core.Tests.dll