using OnionArchitecture.Core.Models;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity.ModelConfiguration;

namespace OnionArchitecture.Repository.EntityFramework.Mapping
{
    public abstract class AutoGeneratedIdentityEntityMap<T> : EntityTypeConfiguration<T> 
                where T : EntityBase<int>
    {
        protected AutoGeneratedIdentityEntityMap()
        {
            Property(c => c.Id).HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
        }
    }
}
